version: '3.3'

services:
  prometheus:
    image: ${USER_NAME:-user}/prometheus
    ports:
      - ${PROMETHEUS_PUBLISHED_PORT:-9090}:9090/tcp
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'
    networks:
      - front_net

  node-exporter:
    image: prom/node-exporter:${NODE_EXPORTER_VERSION:-v0.15.2}
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks:
      - front_net

  mongodb-exporter:
    image: ${USER_NAME:-user}/mongodb-exporter
    command:
      - '--collect.database'
      - '--collect.collection'
      - '--collect.topmetrics'
      - '--collect.indexusage'
      - '--collect.connpoolstats'
      - '--mongodb.uri=mongodb://mongo_db:27017'
    networks:
      - back_net
      - front_net

  blackbox-exporter:
    image: prom/blackbox-exporter:${BLACKBOX_EXPORTER_VERSION:-v0.16.0}
    networks:
      - front_net

  cloudprober:
    image: ${USER_NAME:-user}/cloudprober
    networks:
      - front_net

  cadvisor:
    image: google/cadvisor:${CADVISOR_VERSION:-v0.29.0}
    volumes:
      - '/:/rootfs:ro'
      - '/var/run:/var/run:rw'
      - '/sys:/sys:ro'
      - '/var/lib/docker/:/var/lib/docker:ro'
    ports:
      - ${CADVISOR_PUBLISHED_PORT:-8080}:8080/tcp
    networks:
      - front_net

  grafana:
    image: ${USER_NAME:-user}/grafana
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=secret
    depends_on:
      - prometheus
    ports:
      - ${GRAFANA_PUBLISHED_PORT:-3000}:3000
    networks:
      - front_net

  alertmanager:
    image: ${USER_NAME:-user}/alertmanager
    volumes:
      - alertmanager_data:/alertmanager
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    ports:
      - ${ALERTMANAGER_PUBLISHED_PORT:-9093}:9093
    networks:
      - front_net

  telegraf:
    image: ${USER_NAME:-user}/telegraf
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - front_net

volumes:
  prometheus_data:
  grafana_data:
  alertmanager_data:

networks:
  back_net:
    ipam:
      config:
        - subnet: ${BACK_SUBNET:-10.0.2.0/24}
  front_net:
    ipam:
      config:
        - subnet: ${FRONT_SUBNET:-10.0.1.0/24}
